import Header from './Components/Header'
import './globals.css'

export const metadata = {
  title: 'Med_Vendors',
  description: 'Generated by KAUSHAL SARAF',
}
export default function RootLayout({ children }) {
  return (
    <html>
      <head>
          <meta name="viewport" content="initial-scale=1, maximum-scale=1" />
      </head>
      <body className='bg-blue-100'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
