"use client"
import './globals.css'
import Header from '@/Components/Header'

export const metadata = {
  title: 'Med_Vendors',
  description: 'Generated by KAUSHAL SARAF',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className='bg-blue-100'>
        <Header/>
        {children}
      </body>
    </html>
  )
}
